name = "rron-car-rental"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "rron-db"
database_id = "f219a065-11bf-46e3-8168-9a5aeb20431d"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "rron-images"

[vars]
ADMIN_SECRET = "ermal123admin"
R2_PUBLIC_URL = "https://pub-b132e3ba0ce84031a678fb66664122c0.r2.dev"
